Al dn welcome prompt
the-collab-lab/tcl-56-smart-shopping-list pull request #23
Opened 2023-04-26 00:34 UTC by alucernoni

## Description

This code adds a welcome prompt that is displayed when a user's list is empty, inviting them to add an item to begin their list. We added an "Add Item" button above the filter for easier accessibility that redirects to the Add Item page. We also created a potato chip graphic (gif) to display the welcome message; and added a List.css file to position "Chippy".

## Related Issue

closes #7 

## Acceptance Criteria

 The list view, when there are no items to display, should show a prompt (e.g., a button) for the user to add their first item

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓ | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before

<img width="1432" alt="Screen Shot 2023-04-25 at 5 32 35 PM" src="https://user-images.githubusercontent.com/102399239/234436628-8c2979c3-6329-40e4-8ab7-7ee8d8875295.png">

### After

<img width="1410" alt="Screen Shot 2023-04-25 at 5 31 52 PM" src="https://user-images.githubusercontent.com/102399239/234436650-07712fb1-a740-4e96-b12b-4dbec37d4c49.png">

## Testing Steps / QA Criteria

When you create a new list in the home page, check to see if the welcome message is displayed. It should change to a different suggestion once you have added an item to your list.

2023-04-26 13:59 UTC, yiremorlans commented on src/views/List.jsx
> +					? 'Uh oh! Your shopping list is empty! Try using the "Add Item" button to begin your list!'
Helpful comments for the user

2023-04-26 14:24 UTC, yiremorlans requested changes

2023-04-26 14:24 UTC, yiremorlans commented on src/views/List.css
There are only absolute units of measurement (px) being used for styling. How can we deliver the same layout to a mobile user as a desktop user?

I think responsive design patterns like using % or rems/ems for measurement would prevent the message from being obstructed.   
<img width="600" alt="Screenshot 2023-04-26 at 10 15 05 AM" src="https://user-images.githubusercontent.com/93563580/234603867-ae134ddc-df75-40fb-98fe-be264a58ecde.png">

In a narrow viewport like mobile, we cannot see the messages. 
<img width="497" alt="Screenshot 2023-04-26 at 10 22 48 AM" src="https://user-images.githubusercontent.com/93563580/234606045-ba856183-36af-4c8f-8cc4-532bee859708.png">

2023-04-28 20:55 UTC, fakehouseplant approved these changes

2023-04-28 20:55 UTC, fakehouseplant commented on src/views/List.jsx
> +				style={{
I agree that we should move the styling to css file if possible.

2023-04-29 17:08 UTC, merged